import type { Metadata } from "next";
import { Inter, Sora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/navbar";
import { SiteFooter } from "@/components/site-footer";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});
const sora = Sora({subsets:['latin'],variable:'--font-heading'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", inter.variable, sora.variable)}
    >
      <body className="min-h-full bg-black text-white">
        <div className="flex min-h-full flex-col">
          <Navbar />
          <main className="flex-1">{children}</main>
          <div className="mx-auto w-full max-w-[1480px]">
            <SiteFooter />
          </div>
        </div>
      </body>
    </html>
  );
}
